server:
  port: 8761
  
spring:
  application:
    name: CONFIG-SERVER
  cloud: 
    config:
      server: 
        git: 
          uri: https://github.com/shahshubham180/cloud-config-properties
          clone-on-start: true